#!/bin/bash

# Add Aptitude sources
echo "********************************************"
echo "Adding the repos to /etc/apt/sources.list.d/"
echo "********************************************"

sudo sh -c 'add-apt-repository ppa:git-core/ppa'
sudo sh -c 'add-apt-repository ppa:indicator-multiload/stable-daily'
sudo sh -c 'add-apt-repository ppa:chris-lea/node.js'
sudo sh -c 'add-apt-repository ppa:fossfreedom/byzanz'
sudo sh -c 'add-apt-repository ppa:kilian/f.lux'
sudo sh -c 'add-apt-repository ppa:shutter/ppa'
sudo sh -c 'add-apt-repository ppa:yorba/ppa'
sudo sh -c 'add-apt-repository ppa:ubuntuhandbook1/corebird'
sudo sh -c 'add-apt-repository ppa:nviennot/tmate'
wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
wget -qO - https://d2t3ff60b2tol4.cloudfront.net/services@insynchq.com.gpg.key | sudo apt-key add -
sudo sh -c 'echo "deb http://apt.insynchq.com/ubuntu $(lsb_release -sc) non-free" >> /etc/apt/sources.list.d/insync.list'

# Remove stuff first so it's not updated
sudo apt-get remove -y evolution firefox

# Install software
echo "********************************************"
echo "Installing the software"
echo "********************************************"
sudo apt-get update
sudo apt-get install -y apt-fast
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install -y \
                      build-essential \
                      bison \
                      vim-gtk \
                      vlc \
                      shutter \
                      xclip \
                      unison \
                      kid3-qt \
                      htop \
                      curl \
                      git \
                      git-doc \
                      git-svn \
                      git-gui \
                      gitg \
                      libffi-dev \
                      libreadline-dev \
                      libssl-dev \
                      zlib1g-dev \
                      libncurses5-dev \
                      libxml2-dev \
                      libxslt1-dev \
                      libyaml-dev \
                      libgdbm-dev \
                      indicator-multiload \
                      parallel \
                      fish \
                      silversearcher-ag \
                      unetbootin \
                      fluxgui \
                      byzanz \
                      insync \
                      postgresql-9.4 \
                      pgadmin3 \
                      ttf-ancient-fonts \
                      libxcb1-dev \
                      libxcb-randr0-dev \
                      libx11-dev \
                      autoconf \
                      autopoint \
                      libtool \
                      exuberant-ctags \
                      xdotool \
                      wmctrl \
                      nodejs \
                      geary \
                      california \
                      corebird \
                      openconnect \
                      network-manager-openconnect \
                      network-manager-openconnect-gnome \
                      unity-tweak-tool \
                      laptop-mode-tools \
                      bleachbit \
                      python-software-properties \
                      tmux \
                      tmate

echo "********************************************"
echo "Installing Chrome"
echo "********************************************"
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb

echo "********************************************"
echo "Installing Heroku Toolbelt"
echo "********************************************"
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

source install_virtualbox
source install_sqlite3
