#!/bin/bash

VERSION="1.6.4.4"
SOURCES="/home/jesse/sources"

echo "Installing zlib1g-dev (dependency)"
sudo apt-get install zlib1g-dev

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

echo "Downloading git"
wget http://kernel.org/pub/software/scm/git/git-$VERSION.tar.gz
tar xzf git-$VERSION.tar.gz

cd git-$VERSION/
./configure
make && sudo make install


echo "Adding commands to .bash_alias"
echo "

this() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

alias up=\"git push origin \`this\`\"
alias down=\"git pull origin \`this\`\"
alias uph=\"git push heroku \`this\`\"

" >> ~/.bash_aliases


# change prompt color
echo "Enabling nice color support in the command prompt"
echo "
#Git auto-completion & branch name
source ~/scripts/git-completion.sh

#Custom colors
export PS1='\[\033[0;32m\]\h \[\033[1;36m\]\w\[\033[0;34m\]\$(__git_ps1 \" (%s)\") \[\033[00m\]: '
" >> ~/.bashrc
