#!/bin/bash

cd $HOME/src

version="0.5.1-1"
package="chefdk_${version}_amd64.deb"

if [ ! -e $package ]; then
  echo "Downloading $package"
  wget "https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/${package}"
fi
sudo dpkg -i $package

