#!/bin/bash

SOURCES="/home/`whoami`/sources"
VERSION="0.0.6"

echo "Installing dependencies"
sudo apt-get build-dep gitg


if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

wget ftp://ftp.gnome.org/pub/GNOME/sources/gitg/0.0/gitg-$VERSION.tar.bz2

tar xjf gitg-$VERSION.tar.bz2
cd gitg-$VERSION

./configure
make && sudo make install
