#!/bin/bash

## Credit goes to Michael Greenly: http://j.mp/AjCz4
#

RUBY18="ruby-1.8.7-p174"
RUBYGEMS="rubygems-1.3.5"
RUBY19="ruby-1.9.1-p243"
REE="ruby-enterprise-1.8.7-20090928"
SOURCES="/home/`whoami`/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

## Install Ruby 1.8
#
echo "Installing dependencies for $RUBY19"
sudo apt-get build-dep ruby1.8
echo "Downloading $RUBY18"
wget -c ftp://ftp.ruby-lang.org/pub/ruby/1.8/$RUBY18.tar.gz > /dev/null 2>&1
tar xzf $RUBY18.tar.gz
cd $RUBY18/
echo "Configuring, making and installing $RUBY18"
./configure --prefix=/opt/$RUBY18 --enable-pthread --enable-shared --enable-openssl --enable-readline --enable-zlib  > /dev/null 2>&1
make > /dev/null 2>&1
sudo make install > /dev/null 2>&1

## Install Rubygems for 1.8
#
cd $SOURCES
echo "Downloading & installing $RUBYGEMS"
wget -c http://rubyforge.org/frs/download.php/60718/$RUBYGEMS.tgz > /dev/null 2>&1
tar xzf $RUBYGEMS.tgz
cd $RUBYGEMS/
sudo /opt/$RUBY18/bin/ruby setup.rb

## Install Ruby 1.9
#
cd $SOURCES
echo "Installing dependencies for $RUBY19"
sudo apt-get build-dep ruby1.9
wget -c ftp://ftp.ruby-lang.org/pub/ruby/1.9/$RUBY19.tar.gz  > /dev/null 2>&1
tar xzf $RUBY19.tar.gz

cd $RUBY19/
echo "Configuring, making and installing $RUBY19"
./configure --prefix=/opt/$RUBY19 --enable-pthread --enable-shared > /dev/null 2>&1
make > /dev/null 2>&1
sudo make install > /dev/null 2>&1

## Install Ruby Enterprise Edition
#
cd $SOURCES
echo "Installing $REE"
wget -c http://rubyforge.org/frs/download.php/64475/$REE.tar.gz
tar xzf $REE.tar.gz
sudo ./$REE/installer


echo "Building out the version switching script"
echo "#!/bin/sh

while : # Loop forever
do
cat << !

current = \$(/opt/ruby/bin/ruby --version)

Select Option

1. $RUBY18
2. $RUBY19
3. $REE
4. exit

!

echo -n \" Your choice? : \"
read choice

case \$choice in
1) rm -rf /opt/ruby; ln -s /opt/$RUBY18 /opt/ruby;;
2) rm -rf /opt/ruby; ln -s /opt/$RUBY19 /opt/ruby;;
3) rm -rf /opt/ruby; ln -s /opt/$REE /opt/ruby;;
4) exit;;
*) echo \"\\\"\$choice\" is not valid \\\"; sleep 2 ;;
esac
exit
done
" > ~/select_ruby

echo "Making the switching script executable"
chmod +x ~/select_ruby

echo "Adding the switching script to bash_aliases"
sudo mv ~/select_ruby /usr/local/bin/

## Modify the PATH
#
echo "Modifying the PATH to use active version of Ruby"
echo "export PATH=/opt/ruby/bin:\$PATH" >> ~/.bashrc

echo "Reloading the shell"
source ~/.bashrc



echo "

gem_cmd() {

        BAD_PARAMS=91

        cmd=\$1
        case \"\$cmd\" in
                '+')    cmd='install --no-rdoc --no-ri';;
                '-')    cmd='uninstall';;
                '^')    cmd='update';;
                '^\!')   cmd='update --system';;
        esac

        if [ ! -n \"\$cmd\" ]
        then
                echo \"You need to specify a command and options or gem names\"
                return \$BAD_PARAMS
        fi

        shift
        for x in \$( find /opt -maxdepth 1 -type d -name 'ruby-*' ); do
		echo \"Running \$cmd for \$x\"
                sudo sh -c \"\$x/bin/gem \$cmd \$@\"
        done
}


alias gem+=\"gem_cmd +\"
alias gem-=\"gem_cmd -\"
alias gemup=\"gem_cmd ^\"
alias gemup!=\"gem_cmd ^!\"
" >> ~/.bash_aliases
