#!/bin/bash

BIN="/home/`whoami`/bin"
PAGE="http://code.google.com/p/redis/"

if [ -d $BIN ]
then
  cd $BIN
else
  mkdir $BIN
  cd $BIN
fi

echo "Installing Redis"
package=`curl -s $PAGE | grep 'http://redis.googlecode.com/files/redis' | cut -d\" -f2`
wget -c $package

download=`ls -c redis-* | cut -d" " -f1 | head -n 1`
name=`echo $download | sed 's/.tar.gz//'`

tar xzf $download

cd $name
make

cd ../
rm $download

echo ""
echo ""
echo ""
echo ""
echo "***************************************************************************************"
echo "You can now just run ./redis-server or I suppose you can sudo make install if you want."
echo "***************************************************************************************"
