#!/bin/bash

SOURCES="/home/`whoami`/sources/vpnclient"

echo "Installing libgcrypt11-dev & network-manager-vpnc"
sudo apt-get install libgcrypt11-dev network-manager-vpnc

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

echo "Downloading Cisco Decrypt"
wget http://www.debuntu.org/files/cisco-decrypt.c

echo "Compiling Cisco Decrypt"
gcc -Wall -o cisco-decrypt cisco-decrypt.c $(libgcrypt-config --libs --cflags)

echo "Making output executable"
chmod +x cisco-decrypt

echo "Downloading pcf2vpnc converter"
wget http://svn.unix-ag.uni-kl.de/vpnc/trunk/pcf2vpnc

echo "Making pcf2vpnc executable"
chmod +x pcf2vpnc


