#!/bin/bash

cd $HOME/src

version="$(curl -Ls "https://bintray.com/mitchellh/vagrant/vagrant/_latestVersion" | sed -n 's/^[ \t]*<title>\(.*\)<\/title>/\1/Ip')"
package="vagrant_${version}_x86_64.deb"

if [ ! -e $package ]; then
  echo "Downloading $package"
  wget "https://dl.bintray.com/mitchellh/vagrant/${package}"
fi
sudo dpkg -i $package
