#!/bin/bash

VERSION="1.2.10"
PACKAGE="wireshark-${VERSION}"
SOURCES="/home/`whoami`/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

sudo apt-get install bison flex libpcap-dev
wget http://www.wireshark.org/download/src/${PACKAGE}.tar.bz2
tar xjf ${PACKAGE}.tar.bz2
cd PACKAGE

./configure
make

ehco "you can sudo make install or symlink, whatever you like"
