#!/bin/bash

function url_for_latest_release_from_github {
  user="$1"
  repo="$2"
  package="$3"

  curl -s "https://api.github.com/repos/${user}/${repo}/releases/latest" | \
    jq ".assets | .[] | {name: .name, url: .browser_download_url} | select(.name | test('${package}')) | .url"
}

url=url_for_latest_release_from_github("BurntSushi" "ripgrep" "ripgrep-.*-x86_64-unknown-linux-musl")
