#!/bin/bash

SOURCES="/home/`whoami`/sources"

if [ ! -e /usr/local/bin/git ] 
then
  echo "You need git. Try running install_git"
  exit 0
fi

if [ ! -d $SOURCES ]
then
  mkdir $SOURCES
fi

echo "Creating .vim folders if necessary"
cd $SOURCES
mkdir -p ~/.vim/{autoload,doc,indent,ftdetect,ftplugin,plugin,syntax}

repos=(rails haml git cucumber)

for r in ${repos[*]}; do
	repo="vim-$r"
	echo "Checking $repo"
	if [ -d "$SOURCES/$repo/" ]
	then
		echo "Pulling latest from $repo"
		cd $repo
		git pull origin master
		cd ..
	else
		echo "Cloning repo for $repo"
		git clone git://github.com/tpope/$repo.git
	fi
done

cd $SOURCES
cp -fr vim-*/* ~/.vim
