#!/bin/bash

VERSION="1.7.2.1"
SOURCES="/home/`whoami`/sources"

echo "Installing zlib1g-dev (dependency)"
sudo apt-get install zlib1g-dev

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

current_git=`git --version`

if [ "$current_git" != "git version $VERSION" ]
then

    echo "Downloading git"
    wget http://kernel.org/pub/software/scm/git/git-$VERSION.tar.gz
    tar xzf git-$VERSION.tar.gz

    cd git-$VERSION/
    ./configure
    make && sudo make install

    cd ..
    echo "Installing manpages for git"
    wget http://www.kernel.org/pub/software/scm/git/git-manpages-$VERSION.tar.bz2
    sudo tar xjv -C /usr/local/man -f git-manpages-$VERSION.tar.bz2
else
    echo "****************************************"
    echo "You already have git version $VERSION"
    echo "****************************************"
fi
