#!/bin/bash

VERSION="3081000"
PACKAGE="sqlite-autoconf-$VERSION"
TARBALL="$PACKAGE.tar.gz"

sudo apt-get install -y \
  libsqlite3-dev

cd "$HOME/src"
rm -rf sqlite*
wget http://www.sqlite.org/2015/$TARBALL
tar xzf $TARBALL

cd $PACKAGE
./configure && make && sudo make install
