#!/bin/bash

VERSION="ruby-1.9.1-p243"
SOURCES="/home/jesse/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

wget ftp://ftp.ruby-lang.org/pub/ruby/1.9/$VERSION.tar.gz
tar xzf $VERSION.tar.gz

sudo chown -R jesse:jesse $VERSION*

cd $VERSION/
echo "build..."
./configure && make && sudo make install

echo "build openssl correctly"
cd ext/openssl
sudo ruby extconf.rb
make && sudo make install
