#!/bin/bash

VERSION="linuxx86-11.0.140395"
SOURCES="/home/`whoami`/Downloads"
cd $SOURCES

echo "Installing libmotif3"
sudo apt-get install libmotif3

echo "When you're done downloading the .tar.gz, close the browser, come back to the terminal and hit any key"
sleep 2
firefox http://j.mp/uoOMX & 
read -p "Hit any key when done"

tar -xzf $VERSION.tar.gz
cd $VERSION
sudo ./setupwfc
