#!/bin/bash

VERSION="3.6.23.1"
PACKAGE="sqlite-amalgamation-$VERSION"
SOURCES="/home/`whoami`/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

sudo apt-get install libsqlite3-dev

wget http://www.sqlite.org/$PACKAGE.tar.gz
tar xzf $PACKAGE.tar.gz

cd sqlite-$VERSION/
./configure && make && sudo make install
