#!/bin/bash

echo "Adding commands to .bash_alias"
echo "

alias gemi=\"sudo gem install --no-rdoc --no-ri\"
alias gemu=\"sudo gem uninstall\"
alias gemup=\"sudo gem update\"
alias gemup!=\"sudo gem update --system\"

" >> ~/.bash_aliases
