#!/bin/bash

# Add Aptitude sources
echo "********************************************"
echo "Adding the repos to /etc/apt/sources.list.d/"
echo "********************************************"

sudo sh -c 'add-apt-repository ppa:git-core/ppa'
sudo sh -c 'add-apt-repository ppa:indicator-multiload/stable-daily'

# Remove stuff first so it's not updated
sudo apt-get remove evolution

# Install software
echo "Installing the software"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install build-essential vlc shutter sound-juicer\
    geany xclip tagtool pigz\
    unison kid3-qt htop curl\
    git git-doc git-svn git-gui gitg libffi-dev libvm-dev\
    libreadline-dev libssl-dev zlib1g-dev libncurses5-dev\
    libxml2-dev libxslt1-dev libyaml-dev libgdbm-dev\
    indicator-multiload autopoint\
    libxcb-randr0-dev parallel\
    silversearcher-ag
