#!/bin/bash

# Add Aptitude sources
echo "Adding the repos to /etc/apt/sources.list.d/"

sudo sh -c 'echo "deb http://linux.dropbox.com/ubuntu lucid main
deb-src http://linux.dropbox.com/ubuntu lucid main" > /etc/apt/sources.list.d/dropbox.list'

# Add keys
# This key might be needed in the future
#gpg --keyserver pgp.mit.edu --recv-keys 3565780E

# Install software
echo "Installing the software"
sudo apt-get update
sudo apt-get install nautilus-dropbox

