#!/bin/bash

VERSION="1.6.4"
SOURCES="/home/jesse/sources"

if [ "$UID" -eq 0 ]  # Will the real "root" please stand up?
then
  echo "Proceed..."
else
  echo "You need to be root to run this script. try sudo"
  exit 0
fi

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

wget http://kernel.org/pub/software/scm/git/git-$VERSION.tar.gz
tar xzf git-$VERSION.tar.gz

sudo chown -R jesse:jesse git-$VERSION*

cd git-$VERSION/
./configure
make && sudo make install
