#!/bin/bash

cd /tmp
version="5.2.17-1ubu910"
deb="mysql-workbench-oss-$version-amd64.deb"
package="http://dev.mysql.com/get/Downloads/MySQLGUITools/$deb/from/http://mysql.llarian.net/"

echo "Downloading MySQL Workbench"
wget -c $package

echo ""
echo "Installing"
#sudo apt-get install build-essential autoconf automake libtool libzip-dev libxml2-dev libsigc++-2.0-dev libglade2-dev libgtkmm-2.4-dev libglu1-mesa-dev libgl1-mesa-glx mesa-common-dev libmysqlclient15-dev uuid-dev liblua5.1-dev libpixman-1-dev libpcre3-dev libgnome2-dev libgtk2.0-dev libpango1.0-dev libcairo2-dev python-dev libboost-dev

sudo apt-get install python-pexpect python-paramiko libzip1
sudo dpkg -i $deb
