#!/bin/bash

sudo apt-get install unzip
if [ ! -e /usr/bin/getlibs ]
then
    echo "Installing getlibs & libstdc++5"
    cd /tmp
    wget http://frozenfox.freehostia.com/cappy/getlibs-all.deb
    wget http://nl.archive.ubuntu.com/ubuntu/pool/universe/g/gcc-3.3/libstdc++5_3.3.6-17ubuntu1_i386.deb
    sudo dpkg -i getlibs-all.deb
    getlibs -i libstdc++5_3.3.6-17ubuntu1_i386.deb
fi



cd ~/Desktop
if [ ! -e DPT-Linux.zip ]
then
    wget http://swmirror.org/drupal/files/DPT-Linux.zip
fi
if [ ! -d DPT-Linux ]
then
    unzip DPT-Linux.zip -d DPT-Linux
fi

echo "**************************************************"
echo "You can now double click Dpt-Linux to run the tool"
echo "**************************************************"
sleep 3
nautilus DPT-Linux
