#!/bin/bash

DOTVIM="/home/`whoami`/.vim"
PATHOGEN=9394 # pathogen.vim v1.1

if [ ! -e `which git` ]
then
  echo "You need git. Try running install_git"
  exit 0
fi

if [ ! -d $DOTVIM ]
then
  mkdir $DOTVIM
fi

get_repo() {
    repo=$1
    gh_user=$2
    echo "Checking $repo"
    if [ -d "$DOTVIM/bundle/$repo/" ]
    then
        echo "Pulling latest from $repo"
        cd $DOTVIM/bundle/$repo
        git pull origin master
        cd ..
    else
        echo "Cloning repo for $repo"
        git clone git://github.com/$gh_user/$repo.git
    fi
}

echo "Creating .vim folders if necessary"
cd $DOTVIM/bundle/
mkdir -p $DOTVIM/{autoload,bundle}

tpope_repos=(rails haml git cucumber fugitive vividchalk surround unimpaired abolish repeat)

for r in ${tpope_repos[*]}; do
	repo="vim-$r"
    get_repo $repo "tpope"
done

get_repo "nerdtree" "scrooloose"

cd $DOTVIM/autoload
echo "Fetching latest pathogen.vim"
rm pathogen.vim
wget -c -O pathogen.vim http://www.vim.org/scripts/download_script.php?src_id=$PATHOGEN

echo "Checking to see if pathogen has already been added to .vimrc"
pathogen_cmd="call pathogen#runtime_append_all_bundles()"
contains=`grep "$pathogen_cmd" ~/.vimrc | wc -l`

if [ $contains == 0 ]
then
	echo "Hasn't been added, adding now."
	echo "$pathogen_cmd" >> ~/.vimrc
else
	echo "It was already added. Good to go"
fi
