#!/bin/bash

cd /tmp
VERSION="2.26.3-1"
BASE_URL="http://www.graphviz.org/pub/graphviz/stable/ubuntu/ub9.04/x86_64/"
GV="graphviz_${VERSION}_amd64.deb"
LGVF="libgraphviz4_${VERSION}_amd64.deb"
LGV="libgraphviz-dev_${VERSION}_amd64.deb"

echo "Downloading graphviz"
wget ${BASE_URL}${LGVF}
wget ${BASE_URL}${GV}
wget ${BASE_URL}${LGV}

sudo apt-get install -f liblasi0 libgts-0.7-5 libdevil1c2
sudo dpkg -i $LGVF
sudo dpkg -i $GV
sudo dpkg -i $LGV
