#!/bin/bash

VERSION="3080200"
PACKAGE="sqlite-autoconf-$VERSION"
TARBALL="$PACKAGE.tar.gz"

sudo apt-get install libsqlite3-dev -y

cd "$HOME/src"
rm -rf sqlite*
wget http://www.sqlite.org/2013/$TARBALL
tar xzf $TARBALL

cd $PACKAGE
./configure && make && sudo make install
