#!/bin/bash

## Credit goes to Michael Greenly: http://j.mp/AjCz4
#

RUBY18="ruby-1.8.7-p174"
RUBYGEMS="rubygems-1.3.5"
RUBY19="ruby-1.9.1-p243"
REE="ruby-enterprise-1.8.7-20090928"
SOURCES="/home/`whoami`/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

## Install Ruby 1.8
#
sudo apt-get build-dep ruby1.8
wget -c ftp://ftp.ruby-lang.org/pub/ruby/1.8/$RUBY18.tar.gz
tar xzf $RUBY18.tar.gz
cd $RUBY18/
./configure --prefix=/opt/$RUBY18 --enable-pthread --enable-shared --enable-openssl --enable-readline --enable-zlib
make && sudo make install

## Install Rubygems for 1.8
#
cd $SOURCES
wget -c http://rubyforge.org/frs/download.php/60718/$RUBYGEMS.tgz
tar xzf $RUBYGEMS.tgz
cd $RUBYGEMS/
sudo /opt/$RUBY18/bin/ruby setup.rb

## Install Ruby 1.9
#
cd $SOURCES
sudo apt-get build-dep ruby1.9
wget -c ftp://ftp.ruby-lang.org/pub/ruby/1.9/$RUBY19.tar.gz
tar xzf $RUBY19.tar.gz

cd $RUBY19/
./configure --prefix=/opt/$RUBY19 --enable-pthread --enable-shared
make && sudo make install

## Install Ruby Enterprise Edition
#
cd $SOURCES
wget -c http://rubyforge.org/frs/download.php/64475/$REE.tar.gz
tar xzf $REE.tar.gz
./$REE/installer

echo "
#!/bin/sh

while : # Loop forever
do
cat << !

current = \$(/opt/ruby/bin/ruby --version)

Select Option

1. $RUBY18
2. $RUBY19
3. $REE
4. exit

!

echo -n \" Your choice? : \"
read choice

case \$choice in
1) rm -rf /opt/ruby; ln -s /opt/$RUBY18 /opt/ruby;;
2) rm -rf /opt/ruby; ln -s /opt/$RUBY19 /opt/ruby;;
3) rm -rf /opt/ruby; ln -s /opt/$REE /opt/ruby;;
4) exit;;
*) echo \"\"\$choice\" is not valid \"; sleep 2 ;;
esac
exit
done
" > ~/select_ruby

chmod +x ~/select_ruby

echo "alias select_ruby=\"~/select_ruby\"" >> ~/.bash_aliases

## Modify the PATH
#
echo "export PATH=/opt/ruby/bin:\$PATH" >> ~/.bashrc
