#!/bin/bash

wget https://launchpad.net/ubuntu/+archive/primary/+files/libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb
sudo dpkg -i libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb
rm libgcrypt11_1.5.4-2ubuntu1.1_amd64.deb

# 1. Add the Spotify repository signing key to be able to verify downloaded packages
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D2C19886

# 2. Add the Spotify repository
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list

# 3. Update list of available packages
sudo apt update

# 4. Install Spotify
sudo apt install spotify-client
