#!/bin/bash

SOURCES="/home/`whoami`/sources"
PAGE="http://code.google.com/p/redis/"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

echo "Installing Redis"
package=`curl -s $PAGE | grep 'http://redis.googlecode.com/files/redis' | cut -d\" -f2`
wget -c $package

download=`ls -c redis-* | cut -d" " -f1 | head -n 1`
name=`echo $download | sed 's/.tar.gz//'`

tar xzf $download

cd $name
make

echo "You can now just run ./redis-server or I suppose you can sudo make install if you want."
