#!/bin/bash

VERSION="0.9.1"
USER=`whoami`
SOURCES="/home/$USER/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

sudo apt-get install erlang libcurl4-openssl-dev libicu-dev libmozjs-dev

wget http://mirror.uoregon.edu/apache/couchdb/$VERSION/apache-couchdb-$VERSION.tar.gz
tar xzf apache-couchdb-$VERSION.tar.gz

cd apache-couchdb-$VERSION/
./configure && make && sudo make install
