#!/bin/bash

bin="/home/`whoami`/bin"
current_dir=`pwd`

if [ -d $bin ]
then
  echo "~/bin dir exists"
else
  echo "~/bin dir doesn't exists. Creating now."
  mkdir $bin
fi

ln -s $current_dir/run_tags.rb $bin/run_tags
