#!/bin/bash

SOURCES="$HOME/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

if [ -d "node" ]
then
    echo "Pulling latest"
    cd node
    git pull origin master
else
    echo "Cloning repo"
    git clone git://github.com/ry/node.git
    cd node
fi

mkdir $HOME/local
./configure --prefix=$HOME/local/node
make
make install
make doc

echo "*** Make sure to add $HOME/local/node to the path in ~/.bashrc"

echo "Install npm"

cd $HOME/local
curl https://github.com/isaacs/npm/tarball/master -o npm.tar.gz
tar xf npm.tar.gz
cd npm
make
