#!/bin/bash

if [ ! -e `which nokogiri` ]
then
	echo "You don't have nokogiri installed. Installing now..."
	./install_nokogiri
fi 

echo "Nokogiri is installed, proceeding to install gems"
sudo gem install --no-rdoc --no-ri rspec rspec-rails cucumber webrat
