#!/bin/bash

ME="$(whoami)"
mkdir -p ~/projects
mkdir -p ~/.config

function log {
  msg="$1"
  echo "********************************************"
  echo "$msg"
  echo "********************************************"
  echo ""
}
log "Adding the repos to /etc/apt/sources.list.d/"

function add_ppa {
  ppa="$1"
  pattern="$2"
  if [ -z $(ls /etc/apt/sources.list.d | grep '$pattern') ]; then
    log "Adding $ppa"
    sudo sh -c "add-apt-repository ppa:$ppa"
  fi
}

add_ppa "git-core/ppa" "git"
add_ppa "nviennot/tmate" "tmate"
add_ppa "saiarcot895/myppa" "saiarcot895" # for apt-fast
add_ppa "fish-shell/release-2"

log "Installing the software"
sudo apt-get update
log "Installing apt-fast"
sudo apt-get install -y apt-fast
log "Upgrade"
sudo apt-get upgrade
log "Dist upgrade"
sudo apt-get dist-upgrade

log "Install all the things"
sudo apt-fast install -y \
                      build-essential \
                      bison \
                      vim-gtk \
                      xclip \
                      htop \
                      curl \
                      git \
                      git-doc \
                      git-svn \
                      git-gui \
                      gitg \
                      libffi-dev \
                      libreadline-dev \
                      libssl-dev \
                      zlib1g-dev \
                      libncurses5-dev \
                      libxml2-dev \
                      libxslt1-dev \
                      libyaml-dev \
                      libgdbm-dev \
                      parallel \
                      fish \
                      ttf-ancient-fonts \
                      autoconf \
                      autopoint \
                      libtool \
                      exuberant-ctags \
                      python-software-properties \
                      tmux \
                      tmate

if [ -z "$(which ag)" ]; then
  log "Install silversearcher-ag from swiftsignal"
  ag="the-silver-searcher_0.14-1_amd64.deb"
  wget "http://swiftsignal.com/packages/ubuntu/precise/$ag"
  sudo dpkg -i "$ag"
fi

if [ -z "$(ls ~/.oh-my-fish)" ]; then
  log "Install oh-my-fish"
  git clone git://github.com/bpinto/oh-my-fish.git ~/.oh-my-fish
fi

if [ -z "$(ls ~/projects/dotfiles)" ]; then
  log "Installing dotfiles"
  git clone git://github.com/jc00ke/dotfiles.git ~/projects/dotfiles
  source ~/projects/dotfiles/install
fi

if [ -z "$(ls ~/.vim/bundle/Vundle.vim)" ]; then
  log "Installing Vundle"
  git clone git://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
fi

if [ -z "$(ls ~/.config/fish)" ]; then
  log "Installing fish config"
  cd ~/.config
  git clone git://github.com/jc00ke/fish-config.git fish
  chsh -s /usr/bin/fish
fi


if [ -z "$(ls "/usr/local/share/chruby/chruby.fish")" ]; then
  log "Installing chruby-fish"
  version="0.6.0"
  package="chruby-fish-${version}"
  wget -O "${package}.tar.gz" \
          "https://github.com/JeanMertz/chruby-fish/archive/v${version}.tar.gz"
  tar -xzvf "${package}.tar.gz"
  cd "${package}/"
  sudo make install
fi

log "Installing jq"
wget http://stedolan.github.io/jq/download/linux64/jq
chmod +x jq
sudo mv jq /usr/local/bin/

if [ -z "$(which direnv)" ]; then
  url="$(
    curl -s "https://api.github.com/repos/zimbatm/direnv/releases/latest" | \
    jq '.assets | .[] | { name: .name, url: .browser_download_url } | select(.name == "direnv.linux-amd64") | .url' \
    )"
  wget $url
  chmod +x direnv.linux-amd64
  sudo mv direnv.linux-amd64 /usr/local/bin/direnv
fi

