#!/bin/bash

# Add Aptitude sources

echo "Adding the repos to /etc/apt/sources.list.d/"

sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian lucid non-free" > /etc/apt/sources.list.d/virtualbox.list'

echo "Install the apt-secure key"
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -

sudo apt-get update

sudo apt-get install dkms
echo "Now you might want to sudo apt-get install virtualbox-V.v"
