#!/bin/bash

# Add Aptitude sources
echo "********************************************"
echo "Adding the repos to /etc/apt/sources.list.d/"
echo "********************************************"

sudo sh -c 'echo "# Google repository
deb http://dl.google.com/linux/deb/ stable non-free

# Google testing repository
deb http://dl.google.com/linux/deb/ testing non-free" > /etc/apt/sources.list.d/google.list'

sudo sh -c 'add-apt-repository ppa:git-core/ppa'
sudo sh -c 'add-apt-repository ppa:indicator-multiload/stable-daily'

contains_pdx=`grep "cat.pdx" /etc/apt/sources.list | wc -l`
if [ $contains == 0 ]
    then
        echo "********************************************"
        echo "Adding pdx.edu as mirror"
        echo "********************************************"
        sudo sh -c 'echo "

        deb http://mirrors.cat.pdx.edu/ubuntu/ natty main
        deb-src http://mirrors.cat.pdx.edu/ubuntu/ natty main" >> /etc/apt/sources.list'

    else
        echo "PDX mirror is already activated. Skipping..."
fi


echo "********************************************"
echo "http://www.google.com/chrome for stable version"
echo "********************************************"
sleep 5

# Remove stuff first so it's not updated
sudo apt-get remove evolution

# Install software
echo "Installing the software"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install build-essential vim-gnome vlc synapse shutter sound-juicer\
    filezilla geany xclip tagtool pigz\
    unison sqliteman kid3-qt htop curl\
    compizconfig-settings-manager compiz-fusion-plugins-extra weechat\
    git git-doc git-svn git-gui gitg\
    libreadline6-dev libssl-dev zlib1g-dev\
    libxml2-dev libxslt1-dev\
    indicator-multiload nautilus-open-terminal
