#!/bin/bash

DISTRO="$(lsb_release -sc)"
echo "Adding the repos to /etc/apt/sources.list.d/"

sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $DISTRO contrib" > /etc/apt/sources.list.d/virtualbox.list'

echo "Install the apt-secure key"
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -

sudo apt-get update

sudo apt-get install -y dkms virtualbox-4.3
