#!/bin/bash

SOURCES="/home/`whoami`/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

sudo apt-get install intltool

git clone git://git.gnome.org/meld
cd meld/
make

echo 'alias meld="~/sources/meld/bin/meld"' >> ~/.bash_aliases
source ~/.bashrc
