#!/bin/bash

SOURCES="/home/`whoami`/sources"

if [ -d $SOURCES ]
then
  cd $SOURCES
else
  mkdir $SOURCES
  cd $SOURCES
fi

sudo apt-get install intltool

git clone git://git.gnome.org/meld
cd meld/
make


ln -s ~/sources/meld/bin/meld ~/bin
