#!/bin/bash

# Add Aptitude sources
echo "Adding the repos to /etc/apt/sources.list.d/"
sudo sh -c 'echo "deb http://cran.wustl.edu/bin/linux/ubuntu jaunty/" > /etc/apt/sources.list.d/r.list'

gpg --keyserver subkeys.pgp.net --recv-key E2A11821
gpg -a --export E2A11821 | sudo apt-key add -

# Install software
echo "Installing the software"
sudo apt-get update
sudo apt-get install r-base r-base-dev r-recommended
