#!/bin/sh

while : # Loop forever
do
cat << !

current = $(/opt/ruby/bin/ruby --version)

Select Option

1. ruby-1.8.7-p174
2. ruby-1.9.1-p243
3. exit

!

echo -n " Your choice? : "
read choice

case $choice in
1) rm -rf /opt/ruby; ln -s /opt/ruby-1.8.7-p174 /opt/ruby;;
2) rm -rf /opt/ruby; ln -s /opt/ruby-1.9.1-p243 /opt/ruby;;
3) exit;;
*) echo "\"$choice\" is not valid "; sleep 2 ;;
esac
exit
done
